import assert from "node:assert/strict";import {readFile} from "node:fs/promises";import test from "node:test";
import {parseInspectionInput} from "../../src/server/inspections/inspection-service.ts";
import {parseTechnicalIssueInput} from "../../src/server/issues/technical-issue-service.ts";

const contractId="11111111-1111-4111-8111-111111111111";
test("inspection validation accepts a bounded domain input",()=>{const value=parseInspectionInput({contractId,code:"kt-01",title:"Kiểm tra hiện trường",inspectionDate:"2026-09-09",inspectionType:"TECHNICAL",result:"CONFORMING_WITH_FINDINGS"});assert.equal(value.code,"KT-01");});
test("technical issue completion requires resolution evidence",()=>{assert.throws(()=>parseTechnicalIssueInput({contractId,code:"tt-01",title:"Rò rỉ",description:"Rò tại mặt bích",category:"TECHNICAL",severity:"HIGH",status:"RESOLVED",discoveredDate:"2026-09-09"}),/RESOLVED_ISSUE_REQUIRES_DATE_AND_RESOLUTION/);});
test("inspection and issue routes enforce server-side scoped permissions",async()=>{const files=await Promise.all([readFile(new URL("../../src/app/api/inspections/route.ts",import.meta.url),"utf8"),readFile(new URL("../../src/app/api/inspections/[id]/route.ts",import.meta.url),"utf8"),readFile(new URL("../../src/app/api/issues/route.ts",import.meta.url),"utf8"),readFile(new URL("../../src/app/api/issues/[id]/route.ts",import.meta.url),"utf8")]);assert.match(files[0],/requireContractPermission\(context\.principal,"contract\.acceptance\.update",contract\)/);assert.match(files[1],/requireContractPermission\(context\.principal,"contract\.acceptance\.update",contract\)/);assert.match(files[2],/requireContractPermission\(context\.principal,"contract\.progress\.update",contract\)/);assert.match(files[3],/requireContractPermission\(context\.principal,"contract\.progress\.update",contract\)/);});
test("migration has RLS, audit and cross-contract composite references",async()=>{const sql=await readFile(new URL("../../database/migrations/017_inspections_and_technical_issues.sql",import.meta.url),"utf8");assert.match(sql,/FOREIGN KEY\(inspection_id,contract_id\)/);assert.match(sql,/FOREIGN KEY\(contract_item_id,contract_id\)/);assert.match(sql,/FORCE ROW LEVEL SECURITY/g);assert.match(sql,/inspections_audit/);assert.match(sql,/technical_issues_audit/);assert.match(sql,/contract\.acceptance\.update permission and contract scope are required/);assert.match(sql,/contract\.progress\.update permission and contract scope are required/);});
