import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import test from "node:test";
import {parseMilestoneInput,parseMilestoneVersion} from "../../src/server/milestones/milestone-service.ts";

const base={contractId:"11111111-1111-4111-8111-111111111111",workScopeId:"22222222-2222-4222-8222-222222222222",contractItemId:"33333333-3333-4333-8333-333333333333",ownerUserId:"44444444-4444-4444-8444-444444444444",code:" ms-01 ",name:" Hoàn thành bảo dưỡng ",description:" Mốc thử ",plannedDate:"2026-09-30",forecastDate:"2026-10-02",actualDate:undefined,progressPercent:50,status:"IN_PROGRESS" as const,critical:true,notes:" Theo dõi "};

test("milestone parser normalizes code and rejects unsafe fields",()=>{const parsed=parseMilestoneInput(base);assert.equal(parsed.code,"MS-01");assert.equal(parsed.name,"Hoàn thành bảo dưỡng");assert.throws(()=>parseMilestoneInput({...base,createdBy:"attacker"}));assert.equal(parseMilestoneVersion("2"),2);});
test("completed milestone requires actual date and 100 percent",()=>{assert.throws(()=>parseMilestoneInput({...base,status:"COMPLETED",progressPercent:99,actualDate:"2026-09-29"}));assert.throws(()=>parseMilestoneInput({...base,status:"IN_PROGRESS",actualDate:"2026-09-29"}));assert.doesNotThrow(()=>parseMilestoneInput({...base,status:"COMPLETED",progressPercent:100,actualDate:"2026-09-29"}));});
test("migration 016 uses cross-contract foreign keys, RLS, audit and least privilege",async()=>{const sql=await readFile(new URL("../../database/migrations/016_milestones.sql",import.meta.url),"utf8");assert.match(sql,/FOREIGN KEY\(work_scope_id,contract_id\)/);assert.match(sql,/FOREIGN KEY\(contract_item_id,contract_id\)/);assert.match(sql,/FORCE ROW LEVEL SECURITY/);assert.match(sql,/contract\.progress\.update/);assert.match(sql,/milestones_audit/);assert.doesNotMatch(sql,/GRANT[^;]*DELETE ON tcms\.milestones/i);});
test("milestone routes enforce server-side contract progress permission",async()=>{const collection=await readFile(new URL("../../src/app/api/milestones/route.ts",import.meta.url),"utf8");const item=await readFile(new URL("../../src/app/api/milestones/[id]/route.ts",import.meta.url),"utf8");assert.match(collection,/requireContractPermission\(context\.principal,"contract\.progress\.update",contract\)/);assert.match(item,/requireContractPermission\(context\.principal,"contract\.progress\.update",currentContract\)/);});
test("milestone repository only accepts an active owner",async()=>{const source=await readFile(new URL("../../src/server/milestones/postgres-milestone-repository.ts",import.meta.url),"utf8");assert.match(source,/WHERE id=\$1 AND active/);assert.match(source,/MILESTONE_OWNER_NOT_AVAILABLE/);});
