import { apiError } from "@/server/http/api-response";
import { getRequestContext } from "@/server/http/request-context";
import { requireContractPermission } from "@/server/contracts/contract-api";
import { parseContractGoodsItemInput, parseExpectedVersion } from "@/server/contracts/contract-goods-item-service";
import { PostgresContractGoodsItemRepository } from "@/server/contracts/postgres-contract-goods-item-repository";
import { PostgresContractRepository } from "@/server/contracts/postgres-contract-repository";
import { withSecurityTransaction } from "@/server/db/security-transaction";
type Params={params:Promise<{id:string;goodsItemId:string}>};
export async function PATCH(request:Request,{params}:Params) { try { const context=await getRequestContext(request); const {id,goodsItemId}=await params; const body=await request.json() as {item?:unknown;expectedVersion?:unknown}; const input=parseContractGoodsItemInput(body.item); const version=parseExpectedVersion(body.expectedVersion); const item=await withSecurityTransaction(context,async(client)=>{const contract=await new PostgresContractRepository(client).findById(id); if(!contract)return null; requireContractPermission(context.principal,"contract.identity.update",contract); const repo=new PostgresContractGoodsItemRepository(client); if(!await repo.findById(id,goodsItemId))return null; return repo.update(id,goodsItemId,version,input,context.principal.userId);}); return item?Response.json({item}):Response.json({error:"NOT_FOUND"},{status:404}); } catch(error) { return apiError(error); } }
export async function DELETE(request:Request,{params}:Params) { try { const context=await getRequestContext(request); const {id,goodsItemId}=await params; const version=parseExpectedVersion((await request.json() as {expectedVersion?:unknown}).expectedVersion); const found=await withSecurityTransaction(context,async(client)=>{const contract=await new PostgresContractRepository(client).findById(id); if(!contract)return false; requireContractPermission(context.principal,"contract.identity.update",contract); const repo=new PostgresContractGoodsItemRepository(client); if(!await repo.findById(id,goodsItemId))return false; await repo.delete(id,goodsItemId,version); return true;}); return found?new Response(null,{status:204}):Response.json({error:"NOT_FOUND"},{status:404}); } catch(error) { return apiError(error); } }
