"use client";

import { type FormEvent,useCallback,useEffect,useMemo,useState } from "react";
import { AppHeader } from "@/components/layout/app-header";
import { AppSidebar } from "@/components/layout/app-sidebar";
import type {
  SupervisionAssignmentInput,
  SupervisionDecision,
  SupervisionDecisionInput,
  SupervisionDecisionOptions,
  SupervisionDecisionStatus,
} from "@/types/supervision-decision";

const inputClass="mt-1 h-9 w-full rounded-lg border border-slate-200 bg-white px-3 text-xs outline-none focus:border-blue-500";
const today=()=>new Date().toLocaleDateString("en-CA");
const emptyAssignment=():SupervisionAssignmentInput=>({userId:"",workScopeId:undefined,supervisorRole:"Giám sát",responsibility:"",activeFrom:undefined,activeUntil:undefined});
const emptyForm=():SupervisionDecisionInput=>({contractId:"",decisionNumber:"",decisionDate:today(),title:"Quyết định phân công giám sát hợp đồng",effectiveFrom:today(),effectiveUntil:undefined,status:"DRAFT",notes:"",assignments:[emptyAssignment()]});
const statusLabel:Record<SupervisionDecisionStatus,string>={DRAFT:"Dự thảo",ISSUED:"Đã ban hành",SUPERSEDED:"Đã thay thế",REVOKED:"Đã thu hồi"};
const statusClass:Record<SupervisionDecisionStatus,string>={DRAFT:"bg-amber-50 text-amber-700",ISSUED:"bg-emerald-50 text-emerald-700",SUPERSEDED:"bg-slate-100 text-slate-600",REVOKED:"bg-red-50 text-red-700"};

async function readJson<T>(response:Response):Promise<T>{const body=await response.json().catch(()=>({})) as {message?:string};if(!response.ok)throw new Error(body.message??`Yêu cầu thất bại (${response.status}).`);return body as T;}

function toInput(item:SupervisionDecision):SupervisionDecisionInput{return {contractId:item.contractId,decisionNumber:item.decisionNumber,decisionDate:item.decisionDate,title:item.title,effectiveFrom:item.effectiveFrom,effectiveUntil:item.effectiveUntil,status:item.status,notes:item.notes,assignments:item.assignments.map((entry)=>({userId:entry.userId,workScopeId:entry.workScopeId,supervisorRole:entry.supervisorRole,responsibility:entry.responsibility,activeFrom:entry.activeFrom,activeUntil:entry.activeUntil}))};}

export default function SupervisionDecisionsPage(){
  const [decisions,setDecisions]=useState<SupervisionDecision[]>([]); const [options,setOptions]=useState<SupervisionDecisionOptions>({contracts:[],personnel:[],workScopes:[]});
  const [canManage,setCanManage]=useState(false); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState<string>();
  const [editing,setEditing]=useState<SupervisionDecision>(); const [showForm,setShowForm]=useState(false); const [form,setForm]=useState<SupervisionDecisionInput>(emptyForm());
  const load=useCallback(async()=>{const result=await readJson<{decisions:SupervisionDecision[];options:SupervisionDecisionOptions;capabilities:{canManage:boolean}}>(await fetch("/api/supervision-decisions",{cache:"no-store"}));setDecisions(result.decisions);setOptions(result.options);setCanManage(result.capabilities.canManage);setError(undefined);setLoading(false);},[]);
  useEffect(()=>{let active=true;const timer=window.setTimeout(()=>{void load().catch((reason)=>{if(active){setError(reason instanceof Error?reason.message:"Không thể tải quyết định giám sát.");setLoading(false);}});},0);return()=>{active=false;window.clearTimeout(timer);};},[load]);
  const scopes=useMemo(()=>options.workScopes.filter((item)=>item.contractId===form.contractId),[options.workScopes,form.contractId]);
  function openCreate(){const next=emptyForm();next.contractId=options.contracts[0]?.id??"";setEditing(undefined);setForm(next);setShowForm(true);setError(undefined);}
  function openEdit(item:SupervisionDecision){setEditing(item);setForm(toInput(item));setShowForm(true);setError(undefined);}
  function updateAssignment(index:number,change:Partial<SupervisionAssignmentInput>){setForm((value)=>({...value,assignments:value.assignments.map((item,itemIndex)=>itemIndex===index?{...item,...change}:item)}));}
  async function persist(input:SupervisionDecisionInput,item=editing){if(item){await readJson(await fetch(`/api/supervision-decisions/${encodeURIComponent(item.id)}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({decision:input,expectedVersion:item.version})}));}else{await readJson(await fetch("/api/supervision-decisions",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(input)}));}}
  async function save(event:FormEvent){event.preventDefault();setSaving(true);setError(undefined);try{await persist(form);setShowForm(false);await load();}catch(reason){setError(reason instanceof Error?reason.message:"Không thể lưu quyết định.");}finally{setSaving(false);}}
  async function closeDecision(item:SupervisionDecision,status:"REVOKED"|"SUPERSEDED"){setSaving(true);setError(undefined);try{await persist({...toInput(item),status},item);await load();}catch(reason){setError(reason instanceof Error?reason.message:"Không thể đổi trạng thái quyết định.");}finally{setSaving(false);}}

  return <div className="min-h-screen bg-slate-100"><AppHeader/><div className="flex"><AppSidebar/><main className="min-w-0 flex-1 p-4"><div className="mx-auto max-w-7xl">
    <div className="flex items-start justify-between gap-3"><div><h1 className="text-xl font-bold text-slate-900">Quyết định giám sát</h1><p className="mt-1 text-xs text-slate-500">Quản lý quyết định và phân công nhân sự theo hợp đồng, phạm vi công việc.</p></div>{canManage&&<button onClick={openCreate} className="rounded-lg bg-blue-700 px-3 py-2 text-xs font-semibold text-white">+ Thêm quyết định</button>}</div>
    {error&&<p className="mt-3 rounded-lg border border-red-200 bg-red-50 p-3 text-xs text-red-700">{error}</p>}
    <div className="mt-4 grid gap-3 sm:grid-cols-3"><div className="rounded-xl border bg-white p-4"><p className="text-[10px] text-slate-500">Tổng quyết định</p><p className="text-2xl font-bold">{decisions.length}</p></div><div className="rounded-xl border bg-white p-4"><p className="text-[10px] text-slate-500">Đang hiệu lực</p><p className="text-2xl font-bold text-emerald-700">{decisions.filter((item)=>item.status==="ISSUED").length}</p></div><div className="rounded-xl border bg-white p-4"><p className="text-[10px] text-slate-500">Lượt phân công</p><p className="text-2xl font-bold text-blue-700">{decisions.reduce((sum,item)=>sum+item.assignments.length,0)}</p></div></div>
    {showForm&&<form onSubmit={save} className="mt-4 rounded-xl border border-blue-100 bg-white p-4"><div className="flex items-center justify-between"><div><h2 className="text-sm font-bold">{editing?"Chỉnh sửa dự thảo":"Thêm quyết định giám sát"}</h2><p className="mt-1 text-[10px] text-slate-500">Quyết định đã ban hành không được sửa nội dung; chỉ có thể thay thế hoặc thu hồi.</p></div><button type="button" onClick={()=>setShowForm(false)} className="text-xs text-slate-500">Đóng</button></div>
      <div className="mt-4 grid gap-3 md:grid-cols-2 lg:grid-cols-4"><label className="text-[11px] font-semibold lg:col-span-2">Hợp đồng *<select required disabled={Boolean(editing)} className={inputClass} value={form.contractId} onChange={(event)=>setForm((value)=>({...value,contractId:event.target.value,assignments:value.assignments.map((item)=>({...item,workScopeId:undefined}))}))}><option value="">Chọn hợp đồng</option>{options.contracts.map((item)=><option key={item.id} value={item.id}>{item.contractNumber} - {item.packageName}</option>)}</select></label><label className="text-[11px] font-semibold">Số quyết định *<input required maxLength={120} className={inputClass} value={form.decisionNumber} onChange={(event)=>setForm((value)=>({...value,decisionNumber:event.target.value}))}/></label><label className="text-[11px] font-semibold">Ngày quyết định *<input required type="date" className={inputClass} value={form.decisionDate} onChange={(event)=>setForm((value)=>({...value,decisionDate:event.target.value}))}/></label><label className="text-[11px] font-semibold md:col-span-2 lg:col-span-4">Tên/trích yếu quyết định *<input required maxLength={500} className={inputClass} value={form.title} onChange={(event)=>setForm((value)=>({...value,title:event.target.value}))}/></label><label className="text-[11px] font-semibold">Hiệu lực từ *<input required type="date" className={inputClass} value={form.effectiveFrom} onChange={(event)=>setForm((value)=>({...value,effectiveFrom:event.target.value}))}/></label><label className="text-[11px] font-semibold">Hiệu lực đến<input type="date" className={inputClass} value={form.effectiveUntil??""} onChange={(event)=>setForm((value)=>({...value,effectiveUntil:event.target.value||undefined}))}/></label><label className="text-[11px] font-semibold">Trạng thái<select className={inputClass} value={form.status} onChange={(event)=>setForm((value)=>({...value,status:event.target.value as SupervisionDecisionStatus}))}><option value="DRAFT">Dự thảo</option><option value="ISSUED">Đã ban hành</option></select></label><label className="text-[11px] font-semibold lg:col-span-4">Ghi chú<textarea maxLength={2000} className="mt-1 min-h-16 w-full rounded-lg border border-slate-200 p-3 text-xs outline-none focus:border-blue-500" value={form.notes??""} onChange={(event)=>setForm((value)=>({...value,notes:event.target.value}))}/></label></div>
      <div className="mt-4 border-t pt-4"><div className="flex items-center justify-between"><div><h3 className="text-xs font-bold">Nhân sự được phân công</h3><p className="mt-1 text-[10px] text-slate-500">Để trống phạm vi nếu nhân sự giám sát toàn bộ hợp đồng.</p></div><button type="button" onClick={()=>setForm((value)=>({...value,assignments:[...value.assignments,emptyAssignment()]}))} className="text-xs font-semibold text-blue-700">+ Thêm người</button></div><div className="mt-3 space-y-3">{form.assignments.map((item,index)=><div key={index} className="grid gap-2 rounded-lg bg-slate-50 p-3 md:grid-cols-2 lg:grid-cols-6"><label className="text-[10px] font-semibold lg:col-span-2">Nhân sự *<select required className={inputClass} value={item.userId} onChange={(event)=>updateAssignment(index,{userId:event.target.value})}><option value="">Chọn nhân sự</option>{options.personnel.map((person)=><option key={person.id} value={person.id}>{person.displayName}{person.departmentCode?` - ${person.departmentCode}`:""}</option>)}</select></label><label className="text-[10px] font-semibold lg:col-span-2">Phạm vi công việc<select className={inputClass} value={item.workScopeId??""} onChange={(event)=>updateAssignment(index,{workScopeId:event.target.value||undefined})}><option value="">Toàn bộ hợp đồng</option>{scopes.map((scope)=><option key={scope.id} value={scope.id}>{scope.code?`${scope.code} - `:""}{scope.name}</option>)}</select></label><label className="text-[10px] font-semibold lg:col-span-2">Vai trò *<input required maxLength={120} className={inputClass} value={item.supervisorRole} onChange={(event)=>updateAssignment(index,{supervisorRole:event.target.value})}/></label><label className="text-[10px] font-semibold lg:col-span-2">Nhiệm vụ cụ thể<input maxLength={1000} className={inputClass} value={item.responsibility??""} onChange={(event)=>updateAssignment(index,{responsibility:event.target.value})}/></label><label className="text-[10px] font-semibold">Từ ngày<input type="date" className={inputClass} value={item.activeFrom??""} onChange={(event)=>updateAssignment(index,{activeFrom:event.target.value||undefined})}/></label><label className="text-[10px] font-semibold">Đến ngày<input type="date" className={inputClass} value={item.activeUntil??""} onChange={(event)=>updateAssignment(index,{activeUntil:event.target.value||undefined})}/></label><div className="flex items-end lg:col-span-2"><button type="button" disabled={form.assignments.length===1} onClick={()=>setForm((value)=>({...value,assignments:value.assignments.filter((_,itemIndex)=>itemIndex!==index)}))} className="h-9 text-xs font-semibold text-red-600 disabled:text-slate-300">Xóa phân công</button></div></div>)}</div></div>
      <div className="mt-4 flex justify-end gap-2 border-t pt-4"><button type="button" onClick={()=>setShowForm(false)} className="h-9 rounded-lg border px-4 text-xs">Hủy</button><button disabled={saving} className="h-9 rounded-lg bg-blue-700 px-4 text-xs font-semibold text-white disabled:opacity-60">{saving?"Đang lưu...":"Lưu quyết định"}</button></div>
    </form>}
    <section className="mt-4 overflow-hidden rounded-xl border border-slate-200 bg-white"><div className="border-b px-4 py-3"><h2 className="text-sm font-bold">Danh sách quyết định</h2>{!canManage&&<p className="mt-1 text-[10px] text-slate-500">Tài khoản hiện tại được xem các quyết định trong phạm vi nhưng không có quyền phân công.</p>}</div><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="bg-slate-50 text-[10px] uppercase text-slate-500"><tr><th className="px-4 py-3">Quyết định</th><th className="px-4 py-3">Hợp đồng</th><th className="px-4 py-3">Hiệu lực</th><th className="px-4 py-3">Phân công</th><th className="px-4 py-3">Trạng thái</th>{canManage&&<th className="px-4 py-3 text-right">Thao tác</th>}</tr></thead><tbody className="divide-y">{decisions.map((item)=><tr key={item.id}><td className="px-4 py-3"><p className="font-bold text-blue-700">{item.decisionNumber}</p><p className="mt-1 max-w-xs text-[10px] text-slate-500">{item.title}</p></td><td className="px-4 py-3"><p className="font-semibold">{item.contractNumber}</p><p className="mt-1 max-w-xs truncate text-[10px] text-slate-500">{item.packageName}</p></td><td className="px-4 py-3"><p>{item.effectiveFrom}</p><p className="mt-1 text-[10px] text-slate-500">đến {item.effectiveUntil??"không thời hạn"}</p></td><td className="px-4 py-3"><p className="font-semibold">{item.assignments.length} người</p><p className="mt-1 max-w-sm text-[10px] text-slate-500">{item.assignments.map((entry)=>entry.displayName).join(", ")}</p></td><td className="px-4 py-3"><span className={`rounded-full px-2 py-1 text-[10px] font-semibold ${statusClass[item.status]}`}>{statusLabel[item.status]}</span></td>{canManage&&<td className="whitespace-nowrap px-4 py-3 text-right">{item.status==="DRAFT"&&<button onClick={()=>openEdit(item)} className="font-semibold text-blue-700">Sửa</button>}{item.status==="ISSUED"&&<><button disabled={saving} onClick={()=>void closeDecision(item,"SUPERSEDED")} className="mr-3 font-semibold text-slate-600">Thay thế</button><button disabled={saving} onClick={()=>void closeDecision(item,"REVOKED")} className="font-semibold text-red-600">Thu hồi</button></>}</td>}</tr>)}{!loading&&decisions.length===0&&<tr><td colSpan={6} className="p-8 text-center text-slate-500">Chưa có quyết định giám sát.</td></tr>}</tbody></table>{loading&&<p className="p-8 text-center text-xs text-slate-500">Đang tải dữ liệu...</p>}</div></section>
  </div></main></div></div>;
}
