"use client";

import { type FormEvent,useCallback,useEffect,useState } from "react";
import { AppHeader } from "@/components/layout/app-header";
import { AppSidebar } from "@/components/layout/app-sidebar";
import type { Contractor,ContractorInput } from "@/types/contractor";

const emptyForm:ContractorInput={code:"",name:"",taxCode:"",address:"",phone:"",representative:"",active:true};
const inputClass="mt-1 h-9 w-full rounded-lg border border-slate-200 bg-white px-3 text-xs outline-none focus:border-blue-500";

async function readJson<T>(response:Response):Promise<T>{const body=await response.json().catch(()=>({})) as {message?:string};if(!response.ok)throw new Error(body.message??`Yêu cầu thất bại (${response.status}).`);return body as T;}

export default function ContractorsPage(){
  const [contractors,setContractors]=useState<Contractor[]>([]); const [canManage,setCanManage]=useState(false);
  const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState<string>();
  const [editing,setEditing]=useState<Contractor>(); const [form,setForm]=useState<ContractorInput>(emptyForm); const [showForm,setShowForm]=useState(false);
  const load=useCallback(async()=>{const result=await readJson<{contractors:Contractor[];capabilities:{canManage:boolean}}>(await fetch("/api/contractors",{cache:"no-store"}));setContractors(result.contractors);setCanManage(result.capabilities.canManage);setError(undefined);setLoading(false);},[]);
  useEffect(()=>{let active=true;const timer=window.setTimeout(()=>{void load().catch((reason)=>{if(active){setError(reason instanceof Error?reason.message:"Không thể tải nhà thầu.");setLoading(false);}});},0);return()=>{active=false;window.clearTimeout(timer);};},[load]);
  function openCreate(){setEditing(undefined);setForm(emptyForm);setShowForm(true);setError(undefined);}
  function openEdit(item:Contractor){setEditing(item);setForm({code:item.code,name:item.name,taxCode:item.taxCode??"",address:item.address??"",phone:item.phone??"",representative:item.representative??"",active:item.active});setShowForm(true);setError(undefined);}
  async function save(event:FormEvent){event.preventDefault();setSaving(true);setError(undefined);try{if(editing){await readJson(await fetch(`/api/contractors/${encodeURIComponent(editing.id)}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({contractor:form,expectedVersion:editing.version})}));}else{await readJson(await fetch("/api/contractors",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)}));}setShowForm(false);await load();}catch(reason){setError(reason instanceof Error?reason.message:"Không thể lưu nhà thầu.");}finally{setSaving(false);}}
  async function toggle(item:Contractor){setError(undefined);try{await readJson(await fetch(`/api/contractors/${encodeURIComponent(item.id)}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({contractor:{code:item.code,name:item.name,taxCode:item.taxCode,address:item.address,phone:item.phone,representative:item.representative,active:!item.active},expectedVersion:item.version})}));await load();}catch(reason){setError(reason instanceof Error?reason.message:"Không thể đổi trạng thái nhà thầu.");}}
  return <div className="min-h-screen bg-slate-100"><AppHeader/><div className="flex"><AppSidebar/><main className="min-w-0 flex-1 p-4"><div className="mx-auto max-w-7xl">
    <div className="flex items-start justify-between gap-3"><div><h1 className="text-xl font-bold text-slate-900">Danh mục nhà thầu</h1><p className="mt-1 text-xs text-slate-500">Quản lý pháp nhân/đơn vị thực hiện dùng chung cho các hợp đồng.</p></div>{canManage&&<button onClick={openCreate} className="rounded-lg bg-blue-700 px-3 py-2 text-xs font-semibold text-white">+ Thêm nhà thầu</button>}</div>
    {error&&<p className="mt-3 rounded-lg border border-red-200 bg-red-50 p-3 text-xs text-red-700">{error}</p>}
    <div className="mt-4 grid grid-cols-3 gap-3"><div className="rounded-xl border bg-white p-4"><p className="text-[10px] text-slate-500">Tổng nhà thầu</p><p className="text-2xl font-bold">{contractors.length}</p></div><div className="rounded-xl border bg-white p-4"><p className="text-[10px] text-slate-500">Đang hoạt động</p><p className="text-2xl font-bold text-emerald-700">{contractors.filter((item)=>item.active).length}</p></div><div className="rounded-xl border bg-white p-4"><p className="text-[10px] text-slate-500">Hợp đồng đang liên kết</p><p className="text-2xl font-bold text-blue-700">{contractors.reduce((sum,item)=>sum+item.contractCount,0)}</p></div></div>
    {showForm&&<form onSubmit={save} className="mt-4 rounded-xl border border-blue-100 bg-white p-4"><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-3"><label className="text-[11px] font-semibold">Mã nhà thầu *<input required maxLength={40} className={inputClass} value={form.code} onChange={(event)=>setForm((value)=>({...value,code:event.target.value}))}/></label><label className="text-[11px] font-semibold lg:col-span-2">Tên nhà thầu/đơn vị *<input required maxLength={300} className={inputClass} value={form.name} onChange={(event)=>setForm((value)=>({...value,name:event.target.value}))}/></label><label className="text-[11px] font-semibold">Mã số thuế<input maxLength={40} className={inputClass} value={form.taxCode??""} onChange={(event)=>setForm((value)=>({...value,taxCode:event.target.value}))}/></label><label className="text-[11px] font-semibold">Người đại diện/liên hệ<input maxLength={200} className={inputClass} value={form.representative??""} onChange={(event)=>setForm((value)=>({...value,representative:event.target.value}))}/></label><label className="text-[11px] font-semibold">Số điện thoại<input maxLength={50} className={inputClass} value={form.phone??""} onChange={(event)=>setForm((value)=>({...value,phone:event.target.value}))}/></label><label className="text-[11px] font-semibold md:col-span-2 lg:col-span-3">Địa chỉ<input maxLength={500} className={inputClass} value={form.address??""} onChange={(event)=>setForm((value)=>({...value,address:event.target.value}))}/></label></div><div className="mt-4 flex items-center justify-between border-t pt-4"><label className="flex items-center gap-2 text-xs font-semibold"><input type="checkbox" checked={form.active} onChange={(event)=>setForm((value)=>({...value,active:event.target.checked}))}/> Đang hoạt động</label><div className="flex gap-2"><button type="button" onClick={()=>setShowForm(false)} className="h-9 rounded-lg border px-4 text-xs">Hủy</button><button disabled={saving} className="h-9 rounded-lg bg-blue-700 px-4 text-xs font-semibold text-white disabled:opacity-60">{saving?"Đang lưu...":"Lưu"}</button></div></div></form>}
    <section className="mt-4 overflow-hidden rounded-xl border border-slate-200 bg-white"><div className="border-b px-4 py-3"><h2 className="text-sm font-bold">Danh sách nhà thầu</h2>{!canManage&&<p className="mt-1 text-[10px] text-slate-500">Tài khoản hiện tại được tra cứu nhưng không có quyền thay đổi danh mục.</p>}</div><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="bg-slate-50 text-[10px] uppercase text-slate-500"><tr><th className="px-4 py-3">Mã</th><th className="px-4 py-3">Tên nhà thầu</th><th className="px-4 py-3">Mã số thuế / liên hệ</th><th className="px-4 py-3">Hợp đồng</th><th className="px-4 py-3">Trạng thái</th>{canManage&&<th className="px-4 py-3 text-right">Thao tác</th>}</tr></thead><tbody className="divide-y">{contractors.map((item)=><tr key={item.id}><td className="px-4 py-3 font-bold text-blue-700">{item.code}</td><td className="px-4 py-3"><p className="font-semibold">{item.name}</p><p className="mt-1 max-w-sm truncate text-[10px] text-slate-500">{item.address??""}</p></td><td className="px-4 py-3"><p>{item.taxCode??"—"}</p><p className="mt-1 text-[10px] text-slate-500">{item.representative??""}{item.phone?` · ${item.phone}`:""}</p></td><td className="px-4 py-3 font-semibold">{item.contractCount}</td><td className="px-4 py-3"><span className={`rounded-full px-2 py-1 text-[10px] font-semibold ${item.active?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-600"}`}>{item.active?"Hoạt động":"Ngừng sử dụng"}</span></td>{canManage&&<td className="px-4 py-3 text-right"><button onClick={()=>openEdit(item)} className="mr-3 font-semibold text-blue-700">Sửa</button><button onClick={()=>void toggle(item)} className="font-semibold text-slate-600">{item.active?"Ngừng dùng":"Kích hoạt"}</button></td>}</tr>)}{!loading&&contractors.length===0&&<tr><td colSpan={6} className="p-8 text-center text-slate-500">Chưa có nhà thầu.</td></tr>}</tbody></table>{loading&&<p className="p-8 text-center text-xs text-slate-500">Đang tải danh mục...</p>}</div></section>
  </div></main></div></div>;
}
