BEGIN;
DO $$ BEGIN IF EXISTS(SELECT 1 FROM tcms.schema_migrations WHERE version='018_acceptances') THEN RAISE EXCEPTION 'Migration 018_acceptances was already applied';END IF;END $$;
CREATE TABLE tcms.acceptances(
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),contract_id uuid NOT NULL REFERENCES tcms.contracts(id) ON DELETE RESTRICT,work_scope_id uuid,contract_item_id uuid,inspection_id uuid,accepted_by_user_id uuid REFERENCES tcms.app_users(id) ON DELETE RESTRICT,
 code text NOT NULL CHECK(btrim(code)<>''),title text NOT NULL CHECK(btrim(title)<>''),acceptance_type text NOT NULL CHECK(acceptance_type IN ('WORK_VOLUME','QUALITY','STAGE','TECHNICAL_COMPLETION','FINAL')),planned_date date NOT NULL,acceptance_date date,
 result text NOT NULL DEFAULT 'DRAFT' CHECK(result IN ('DRAFT','ACCEPTED','ACCEPTED_WITH_RESERVATIONS','REJECTED','CANCELLED')),accepted_quantity numeric(18,4) CHECK(accepted_quantity IS NULL OR accepted_quantity>=0),unit text,conclusion text,reservations text,
 version integer NOT NULL DEFAULT 1 CHECK(version>0),created_by text NOT NULL,updated_by text NOT NULL,created_at timestamptz NOT NULL DEFAULT clock_timestamp(),updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
 FOREIGN KEY(work_scope_id,contract_id) REFERENCES tcms.work_scopes(id,contract_id) ON DELETE RESTRICT,FOREIGN KEY(contract_item_id,contract_id) REFERENCES tcms.contract_items(id,contract_id) ON DELETE RESTRICT,FOREIGN KEY(inspection_id,contract_id) REFERENCES tcms.inspections(id,contract_id) ON DELETE RESTRICT,
 CHECK((result IN ('ACCEPTED','ACCEPTED_WITH_RESERVATIONS','REJECTED') AND acceptance_date IS NOT NULL AND COALESCE(btrim(conclusion),'')<>'') OR (result NOT IN ('ACCEPTED','ACCEPTED_WITH_RESERVATIONS','REJECTED') AND acceptance_date IS NULL AND conclusion IS NULL AND reservations IS NULL)),
 CHECK(result<>'ACCEPTED_WITH_RESERVATIONS' OR COALESCE(btrim(reservations),'')<>''),CHECK(accepted_quantity IS NULL OR COALESCE(btrim(unit),'')<>'')
);
CREATE UNIQUE INDEX acceptances_contract_code_unique ON tcms.acceptances(contract_id,code);CREATE INDEX acceptances_contract_date_idx ON tcms.acceptances(contract_id,planned_date DESC);CREATE INDEX acceptances_item_idx ON tcms.acceptances(contract_item_id,result) WHERE contract_item_id IS NOT NULL;
CREATE OR REPLACE FUNCTION tcms.touch_acceptance() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN NEW.updated_at:=clock_timestamp();NEW.version:=OLD.version+1;RETURN NEW;END; $$;
CREATE OR REPLACE FUNCTION tcms.enforce_acceptance_write_permission() RETURNS trigger LANGUAGE plpgsql SECURITY INVOKER AS $$ BEGIN IF NOT tcms.has_permission('contract.acceptance.update') OR NOT tcms.can_access_contract(NEW.contract_id) THEN RAISE EXCEPTION 'contract.acceptance.update permission and contract scope are required';END IF;RETURN NEW;END; $$;
CREATE TRIGGER acceptances_touch BEFORE UPDATE ON tcms.acceptances FOR EACH ROW EXECUTE FUNCTION tcms.touch_acceptance();CREATE TRIGGER acceptances_enforce BEFORE INSERT OR UPDATE ON tcms.acceptances FOR EACH ROW EXECUTE FUNCTION tcms.enforce_acceptance_write_permission();CREATE TRIGGER acceptances_audit AFTER INSERT OR UPDATE ON tcms.acceptances FOR EACH ROW EXECUTE FUNCTION tcms.write_row_audit();
ALTER TABLE tcms.acceptances ENABLE ROW LEVEL SECURITY;ALTER TABLE tcms.acceptances FORCE ROW LEVEL SECURITY;
CREATE POLICY acceptances_select ON tcms.acceptances FOR SELECT USING(tcms.has_permission('contract.read') AND tcms.can_access_contract(contract_id));CREATE POLICY acceptances_insert ON tcms.acceptances FOR INSERT WITH CHECK(tcms.has_permission('contract.acceptance.update') AND tcms.can_access_contract(contract_id));CREATE POLICY acceptances_update ON tcms.acceptances FOR UPDATE USING(tcms.has_permission('contract.acceptance.update') AND tcms.can_access_contract(contract_id)) WITH CHECK(tcms.has_permission('contract.acceptance.update') AND tcms.can_access_contract(contract_id));
GRANT SELECT,INSERT,UPDATE ON tcms.acceptances TO tcms_app_runtime;INSERT INTO tcms.schema_migrations(version) VALUES('018_acceptances');COMMIT;
