import "server-only";
import type {PoolClient} from "pg";
import type {TechnicalIssue,TechnicalIssueInput,TechnicalIssueOptions,TechnicalIssueSummary} from "../../types/technical-issue";

const optional=(value:unknown)=>value===null?undefined:String(value);const date=(value:unknown)=>value instanceof Date?value.toISOString().slice(0,10):String(value).slice(0,10);
const select=`SELECT q.*,c.contract_number,c.package_name,x.code inspection_code,w.name work_scope_name,i.item_name contract_item_name,u.display_name assignee_display_name,
  CASE WHEN q.due_date<current_date AND q.status NOT IN ('RESOLVED','CLOSED','CANCELLED') THEN (current_date-q.due_date)::int ELSE 0 END overdue_days
  FROM tcms.technical_issues q JOIN tcms.contracts c ON c.id=q.contract_id LEFT JOIN tcms.inspections x ON x.id=q.inspection_id
  LEFT JOIN tcms.work_scopes w ON w.id=q.work_scope_id LEFT JOIN tcms.contract_items i ON i.id=q.contract_item_id LEFT JOIN tcms.app_users u ON u.id=q.assignee_user_id WHERE true`;
function map(row:Record<string,unknown>):TechnicalIssue{return {id:String(row.id),contractId:String(row.contract_id),contractNumber:String(row.contract_number),packageName:String(row.package_name),inspectionId:optional(row.inspection_id),inspectionCode:optional(row.inspection_code),workScopeId:optional(row.work_scope_id),workScopeName:optional(row.work_scope_name),contractItemId:optional(row.contract_item_id),contractItemName:optional(row.contract_item_name),assigneeUserId:optional(row.assignee_user_id),assigneeDisplayName:optional(row.assignee_display_name),code:String(row.code),title:String(row.title),description:String(row.description),category:row.category as TechnicalIssue["category"],severity:row.severity as TechnicalIssue["severity"],status:row.status as TechnicalIssue["status"],discoveredDate:date(row.discovered_date),dueDate:row.due_date?date(row.due_date):undefined,resolvedDate:row.resolved_date?date(row.resolved_date):undefined,resolution:optional(row.resolution),overdueDays:Number(row.overdue_days),version:Number(row.version),createdAt:String(row.created_at),updatedAt:String(row.updated_at)};}
function dbError(error:unknown):never{if(typeof error==="object"&&error!==null&&"code" in error){if(error.code==="23505")throw new Error("TECHNICAL_ISSUE_CODE_CONFLICT");if(error.code==="23503")throw new Error("TECHNICAL_ISSUE_REFERENCE_NOT_FOUND");if(error.code==="23514")throw new SyntaxError("INVALID_TECHNICAL_ISSUE_FIELDS");}throw error;}

export class PostgresTechnicalIssueRepository{
  constructor(private readonly client:PoolClient){}
  async list(){const result=await this.client.query(`${select} ORDER BY CASE q.severity WHEN 'CRITICAL' THEN 1 WHEN 'HIGH' THEN 2 WHEN 'MEDIUM' THEN 3 ELSE 4 END,q.due_date NULLS LAST,q.discovered_date DESC`);return result.rows.map(map);}
  async findById(id:string){const result=await this.client.query(`${select} AND q.id=$1`,[id]);return result.rowCount?map(result.rows[0]):null;}
  async summary():Promise<TechnicalIssueSummary>{const result=await this.client.query(`SELECT count(*)::int total,count(*) FILTER(WHERE status IN ('OPEN','IN_PROGRESS','PENDING_VERIFICATION'))::int open,count(*) FILTER(WHERE due_date<current_date AND status NOT IN ('RESOLVED','CLOSED','CANCELLED'))::int overdue,count(*) FILTER(WHERE severity='CRITICAL' AND status NOT IN ('RESOLVED','CLOSED','CANCELLED'))::int critical_open,count(*) FILTER(WHERE status IN ('RESOLVED','CLOSED'))::int resolved FROM tcms.technical_issues`);const r=result.rows[0];return {total:Number(r.total),open:Number(r.open),overdue:Number(r.overdue),criticalOpen:Number(r.critical_open),resolved:Number(r.resolved)};}
  async options(includePersonnel:boolean):Promise<TechnicalIssueOptions>{const [contracts,inspections,scopes,items,personnel]=await Promise.all([
    this.client.query("SELECT id::text,contract_number,package_name FROM tcms.contracts WHERE archived_at IS NULL ORDER BY contract_number"),this.client.query("SELECT id::text,contract_id::text,code,title FROM tcms.inspections ORDER BY inspection_date DESC"),this.client.query("SELECT id::text,contract_id::text,code,name FROM tcms.work_scopes ORDER BY contract_id,sequence"),this.client.query("SELECT id::text,contract_id::text,work_scope_id::text,item_code,item_name FROM tcms.contract_items WHERE archived_at IS NULL ORDER BY contract_id,sequence_number"),includePersonnel?this.client.query("SELECT u.id::text,u.display_name,d.code department_code FROM tcms.app_users u LEFT JOIN tcms.departments d ON d.id=u.primary_department_id WHERE u.active ORDER BY u.display_name"):Promise.resolve({rows:[]})]);
    return {contracts:contracts.rows.map((r)=>({id:String(r.id),contractNumber:String(r.contract_number),packageName:String(r.package_name)})),inspections:inspections.rows.map((r)=>({id:String(r.id),contractId:String(r.contract_id),code:String(r.code),title:String(r.title)})),workScopes:scopes.rows.map((r)=>({id:String(r.id),contractId:String(r.contract_id),code:optional(r.code),name:String(r.name)})),contractItems:items.rows.map((r)=>({id:String(r.id),contractId:String(r.contract_id),workScopeId:optional(r.work_scope_id),itemCode:optional(r.item_code),name:String(r.item_name)})),personnel:personnel.rows.map((r)=>({id:String(r.id),displayName:String(r.display_name),departmentCode:optional(r.department_code)}))};}
  async create(input:TechnicalIssueInput,actor:string){try{await this.ensureUser(input.assigneeUserId);const result=await this.client.query(`INSERT INTO tcms.technical_issues(contract_id,inspection_id,work_scope_id,contract_item_id,assignee_user_id,code,title,description,category,severity,status,discovered_date,due_date,resolved_date,resolution,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$16) RETURNING id::text`,[input.contractId,input.inspectionId,input.workScopeId,input.contractItemId,input.assigneeUserId,input.code,input.title,input.description,input.category,input.severity,input.status,input.discoveredDate,input.dueDate,input.resolvedDate,input.resolution,actor]);return (await this.findById(String(result.rows[0].id)))!;}catch(error){return dbError(error);}}
  async update(id:string,version:number,input:TechnicalIssueInput,actor:string){try{await this.ensureUser(input.assigneeUserId);const result=await this.client.query(`UPDATE tcms.technical_issues SET contract_id=$1,inspection_id=$2,work_scope_id=$3,contract_item_id=$4,assignee_user_id=$5,code=$6,title=$7,description=$8,category=$9,severity=$10,status=$11,discovered_date=$12,due_date=$13,resolved_date=$14,resolution=$15,updated_by=$16 WHERE id=$17 AND version=$18 RETURNING id`,[input.contractId,input.inspectionId,input.workScopeId,input.contractItemId,input.assigneeUserId,input.code,input.title,input.description,input.category,input.severity,input.status,input.discoveredDate,input.dueDate,input.resolvedDate,input.resolution,actor,id,version]);if(!result.rowCount)throw new Error("TECHNICAL_ISSUE_CONCURRENT_UPDATE_OR_NOT_FOUND");return (await this.findById(id))!;}catch(error){return dbError(error);}}
  private async ensureUser(id?:string){if(!id)return;const result=await this.client.query("SELECT 1 FROM tcms.app_users WHERE id=$1 AND active",[id]);if(!result.rowCount)throw new Error("TECHNICAL_ISSUE_ASSIGNEE_NOT_AVAILABLE");}
}
