"use client";

import {type FormEvent,useCallback,useEffect,useMemo,useState} from "react";
import {AppHeader} from "@/components/layout/app-header";
import {AppSidebar} from "@/components/layout/app-sidebar";
import type {Inspection,InspectionInput,InspectionOptions,InspectionResult,InspectionSummary,InspectionType} from "@/types/inspection";

const inputClass="mt-1 h-9 w-full rounded-lg border border-slate-200 bg-white px-3 text-xs outline-none focus:border-blue-500";const today=()=>new Date().toLocaleDateString("en-CA");
const empty=():InspectionInput=>({contractId:"",code:"",title:"",inspectionDate:today(),inspectionType:"ROUTINE",result:"PENDING"});
const resultLabels:Record<InspectionResult,string>={PENDING:"Chờ kết luận",CONFORMING:"Đạt",CONFORMING_WITH_FINDINGS:"Đạt có tồn tại",NONCONFORMING:"Không đạt",CANCELLED:"Hủy"};
const resultColors:Record<InspectionResult,string>={PENDING:"bg-slate-100 text-slate-600",CONFORMING:"bg-emerald-50 text-emerald-700",CONFORMING_WITH_FINDINGS:"bg-amber-50 text-amber-700",NONCONFORMING:"bg-red-50 text-red-700",CANCELLED:"bg-slate-100 text-slate-500"};
const typeLabels:Record<InspectionType,string>={ROUTINE:"Định kỳ",HOLD_POINT:"Điểm dừng",WITNESS:"Chứng kiến",TECHNICAL:"Kỹ thuật",SAFETY:"An toàn"};
async function json<T>(response:Response):Promise<T>{const body=await response.json().catch(()=>({})) as {message?:string};if(!response.ok)throw new Error(body.message??`Yêu cầu thất bại (${response.status}).`);return body as T;}
const toInput=(x:Inspection):InspectionInput=>({contractId:x.contractId,workScopeId:x.workScopeId,contractItemId:x.contractItemId,inspectorUserId:x.inspectorUserId,code:x.code,title:x.title,inspectionDate:x.inspectionDate,inspectionType:x.inspectionType,location:x.location,result:x.result,summary:x.summary,recommendations:x.recommendations,nextInspectionDate:x.nextInspectionDate});

export default function InspectionsPage(){
  const [rows,setRows]=useState<Inspection[]>([]);const [summary,setSummary]=useState<InspectionSummary>({total:0,pending:0,withFindings:0,nonconforming:0,thisMonth:0});const [options,setOptions]=useState<InspectionOptions>({contracts:[],workScopes:[],contractItems:[],personnel:[]});const [canManage,setCanManage]=useState(false);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState<string>();const [editing,setEditing]=useState<Inspection>();const [showForm,setShowForm]=useState(false);const [form,setForm]=useState<InspectionInput>(empty());const [contractFilter,setContractFilter]=useState("");const [resultFilter,setResultFilter]=useState("");
  const load=useCallback(async()=>{const data=await json<{inspections:Inspection[];summary:InspectionSummary;options:InspectionOptions;capabilities:{canManage:boolean}}>(await fetch("/api/inspections",{cache:"no-store"}));setRows(data.inspections);setSummary(data.summary);setOptions(data.options);setCanManage(data.capabilities.canManage);setLoading(false);setError(undefined);},[]);
  useEffect(()=>{let active=true;const timer=window.setTimeout(()=>{void load().catch((reason)=>{if(active){setError(reason instanceof Error?reason.message:"Không thể tải phiếu kiểm tra.");setLoading(false);}});},0);return()=>{active=false;window.clearTimeout(timer);};},[load]);
  const scopes=useMemo(()=>options.workScopes.filter((x)=>x.contractId===form.contractId),[options.workScopes,form.contractId]);const items=useMemo(()=>options.contractItems.filter((x)=>x.contractId===form.contractId),[options.contractItems,form.contractId]);const visible=useMemo(()=>rows.filter((x)=>(!contractFilter||x.contractId===contractFilter)&&(!resultFilter||x.result===resultFilter)),[rows,contractFilter,resultFilter]);
  function create(){const next=empty();next.contractId=options.contracts[0]?.id??"";setEditing(undefined);setForm(next);setShowForm(true);setError(undefined);}function edit(row:Inspection){setEditing(row);setForm(toInput(row));setShowForm(true);setError(undefined);}
  async function save(event:FormEvent){event.preventDefault();setSaving(true);setError(undefined);try{if(editing)await json(await fetch(`/api/inspections/${encodeURIComponent(editing.id)}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({inspection:form,expectedVersion:editing.version})}));else await json(await fetch("/api/inspections",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)}));setShowForm(false);await load();}catch(reason){setError(reason instanceof Error?reason.message:"Không thể lưu phiếu kiểm tra.");}finally{setSaving(false);}}
  return <div className="min-h-screen bg-slate-100"><AppHeader/><div className="flex"><AppSidebar/><main className="min-w-0 flex-1 p-4"><div className="mx-auto max-w-7xl">
    <div className="flex items-start justify-between gap-3"><div><h1 className="text-xl font-bold text-slate-900">Kiểm tra & Giám sát</h1><p className="mt-1 text-xs text-slate-500">Lập phiếu, ghi kết luận và liên kết tồn tại với hợp đồng/hạng mục.</p></div>{canManage&&<button onClick={create} className="rounded-lg bg-blue-700 px-3 py-2 text-xs font-semibold text-white">+ Thêm phiếu kiểm tra</button>}</div>
    {error&&<p className="mt-3 rounded-lg border border-red-200 bg-red-50 p-3 text-xs text-red-700">{error}</p>}
    <div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[["Tổng phiếu",summary.total,"text-slate-900"],["Tháng này",summary.thisMonth,"text-blue-700"],["Chờ kết luận",summary.pending,"text-slate-700"],["Có tồn tại",summary.withFindings,"text-amber-700"],["Không đạt",summary.nonconforming,"text-red-700"]].map(([label,value,color])=><div key={String(label)} className="rounded-xl border bg-white p-4"><p className="text-[10px] text-slate-500">{label}</p><p className={`text-2xl font-bold ${color}`}>{value}</p></div>)}</div>
    {showForm&&<form onSubmit={save} className="mt-4 rounded-xl border border-blue-100 bg-white p-4"><div className="flex justify-between"><div><h2 className="text-sm font-bold">{editing?"Chỉnh sửa phiếu kiểm tra":"Thêm phiếu kiểm tra"}</h2><p className="mt-1 text-[10px] text-slate-500">Kết luận có tồn tại nên được liên kết với Vấn đề kỹ thuật để theo dõi xử lý.</p></div><button type="button" onClick={()=>setShowForm(false)} className="text-xs text-slate-500">Đóng</button></div><div className="mt-4 grid gap-3 md:grid-cols-2 lg:grid-cols-4">
      <label className="text-[11px] font-semibold lg:col-span-2">Hợp đồng *<select required disabled={Boolean(editing)} className={inputClass} value={form.contractId} onChange={(e)=>setForm((v)=>({...v,contractId:e.target.value,workScopeId:undefined,contractItemId:undefined}))}><option value="">Chọn hợp đồng</option>{options.contracts.map((x)=><option key={x.id} value={x.id}>{x.contractNumber} - {x.packageName}</option>)}</select></label><label className="text-[11px] font-semibold">Mã phiếu *<input required maxLength={80} className={inputClass} value={form.code} onChange={(e)=>setForm((v)=>({...v,code:e.target.value}))}/></label><label className="text-[11px] font-semibold">Ngày kiểm tra *<input required type="date" className={inputClass} value={form.inspectionDate} onChange={(e)=>setForm((v)=>({...v,inspectionDate:e.target.value}))}/></label>
      <label className="text-[11px] font-semibold lg:col-span-2">Tiêu đề *<input required maxLength={300} className={inputClass} value={form.title} onChange={(e)=>setForm((v)=>({...v,title:e.target.value}))}/></label><label className="text-[11px] font-semibold">Loại kiểm tra<select className={inputClass} value={form.inspectionType} onChange={(e)=>setForm((v)=>({...v,inspectionType:e.target.value as InspectionType}))}>{Object.entries(typeLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label className="text-[11px] font-semibold">Kết luận<select className={inputClass} value={form.result} onChange={(e)=>setForm((v)=>({...v,result:e.target.value as InspectionResult}))}>{Object.entries(resultLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>
      <label className="text-[11px] font-semibold">Phạm vi<select className={inputClass} value={form.workScopeId??""} onChange={(e)=>setForm((v)=>({...v,workScopeId:e.target.value||undefined,contractItemId:undefined}))}><option value="">Toàn hợp đồng</option>{scopes.map((x)=><option key={x.id} value={x.id}>{x.code?`${x.code} - `:""}{x.name}</option>)}</select></label><label className="text-[11px] font-semibold">Hạng mục<select className={inputClass} value={form.contractItemId??""} onChange={(e)=>{const item=items.find((x)=>x.id===e.target.value);setForm((v)=>({...v,contractItemId:item?.id,workScopeId:item?.workScopeId??v.workScopeId}));}}><option value="">Không gắn hạng mục</option>{items.filter((x)=>!form.workScopeId||x.workScopeId===form.workScopeId).map((x)=><option key={x.id} value={x.id}>{x.itemCode?`${x.itemCode} - `:""}{x.name}</option>)}</select></label><label className="text-[11px] font-semibold">Người kiểm tra<select className={inputClass} value={form.inspectorUserId??""} onChange={(e)=>setForm((v)=>({...v,inspectorUserId:e.target.value||undefined}))}><option value="">Chưa chỉ định</option>{options.personnel.map((x)=><option key={x.id} value={x.id}>{x.displayName}{x.departmentCode?` - ${x.departmentCode}`:""}</option>)}</select></label><label className="text-[11px] font-semibold">Kiểm tra tiếp theo<input type="date" className={inputClass} value={form.nextInspectionDate??""} onChange={(e)=>setForm((v)=>({...v,nextInspectionDate:e.target.value||undefined}))}/></label>
      <label className="text-[11px] font-semibold md:col-span-2">Vị trí<input maxLength={300} className={inputClass} value={form.location??""} onChange={(e)=>setForm((v)=>({...v,location:e.target.value}))}/></label><label className="text-[11px] font-semibold md:col-span-2 lg:col-span-4">Nội dung/kết luận<textarea maxLength={4000} className="mt-1 min-h-20 w-full rounded-lg border p-3 text-xs" value={form.summary??""} onChange={(e)=>setForm((v)=>({...v,summary:e.target.value}))}/></label><label className="text-[11px] font-semibold md:col-span-2 lg:col-span-4">Kiến nghị<textarea maxLength={4000} className="mt-1 min-h-16 w-full rounded-lg border p-3 text-xs" value={form.recommendations??""} onChange={(e)=>setForm((v)=>({...v,recommendations:e.target.value}))}/></label>
    </div><div className="mt-4 flex justify-end gap-2 border-t pt-4"><button type="button" onClick={()=>setShowForm(false)} className="h-9 rounded-lg border px-4 text-xs">Hủy</button><button disabled={saving} className="h-9 rounded-lg bg-blue-700 px-4 text-xs font-semibold text-white disabled:opacity-60">{saving?"Đang lưu...":"Lưu phiếu"}</button></div></form>}
    <div className="mt-4 flex flex-wrap gap-2 rounded-xl border bg-white p-3"><select className="h-9 min-w-64 rounded-lg border px-3 text-xs" value={contractFilter} onChange={(e)=>setContractFilter(e.target.value)}><option value="">Tất cả hợp đồng</option>{options.contracts.map((x)=><option key={x.id} value={x.id}>{x.contractNumber}</option>)}</select><select className="h-9 rounded-lg border px-3 text-xs" value={resultFilter} onChange={(e)=>setResultFilter(e.target.value)}><option value="">Tất cả kết luận</option>{Object.entries(resultLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></div>
    <section className="mt-3 overflow-hidden rounded-xl border bg-white"><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="bg-slate-50 text-[10px] uppercase text-slate-500"><tr><th className="px-4 py-3">Phiếu kiểm tra</th><th className="px-4 py-3">Hợp đồng / đối tượng</th><th className="px-4 py-3">Ngày / loại</th><th className="px-4 py-3">Người kiểm tra</th><th className="px-4 py-3">Tồn tại mở</th><th className="px-4 py-3">Kết luận</th>{canManage&&<th className="px-4 py-3 text-right">Thao tác</th>}</tr></thead><tbody className="divide-y">{visible.map((x)=><tr key={x.id}><td className="px-4 py-3"><p className="font-bold text-blue-700">{x.code}</p><p className="mt-1 max-w-xs text-[10px] text-slate-600">{x.title}</p></td><td className="px-4 py-3"><p className="font-semibold">{x.contractNumber}</p><p className="mt-1 text-[10px] text-slate-500">{x.contractItemName??x.workScopeName??"Toàn hợp đồng"}</p></td><td className="px-4 py-3"><p>{x.inspectionDate}</p><p className="mt-1 text-[10px] text-slate-500">{typeLabels[x.inspectionType]}</p></td><td className="px-4 py-3">{x.inspectorDisplayName??"—"}</td><td className="px-4 py-3 font-semibold">{x.openIssueCount}</td><td className="px-4 py-3"><span className={`rounded-full px-2 py-1 text-[10px] font-semibold ${resultColors[x.result]}`}>{resultLabels[x.result]}</span></td>{canManage&&<td className="px-4 py-3 text-right"><button onClick={()=>edit(x)} className="font-semibold text-blue-700">Sửa</button></td>}</tr>)}{!loading&&visible.length===0&&<tr><td colSpan={7} className="p-8 text-center text-slate-500">Chưa có phiếu kiểm tra phù hợp.</td></tr>}</tbody></table>{loading&&<p className="p-8 text-center text-xs text-slate-500">Đang tải dữ liệu...</p>}</div></section>
  </div></main></div></div>;
}
