"use client";

import {type FormEvent,useCallback,useEffect,useMemo,useState} from "react";
import {AppHeader} from "@/components/layout/app-header";
import {AppSidebar} from "@/components/layout/app-sidebar";
import type {Milestone,MilestoneInput,MilestoneOptions,MilestoneStatus,MilestoneSummary} from "@/types/milestone";

const inputClass="mt-1 h-9 w-full rounded-lg border border-slate-200 bg-white px-3 text-xs outline-none focus:border-blue-500";
const today=()=>new Date().toLocaleDateString("en-CA");
const emptyForm=():MilestoneInput=>({contractId:"",workScopeId:undefined,contractItemId:undefined,ownerUserId:undefined,code:"",name:"",description:"",plannedDate:today(),forecastDate:undefined,actualDate:undefined,progressPercent:0,status:"NOT_STARTED",critical:false,notes:""});
const labels:Record<MilestoneStatus,string>={NOT_STARTED:"Chưa bắt đầu",IN_PROGRESS:"Đang thực hiện",AT_RISK:"Có nguy cơ",DELAYED:"Chậm",COMPLETED:"Hoàn thành",CANCELLED:"Hủy"};
const colors:Record<MilestoneStatus,string>={NOT_STARTED:"bg-slate-100 text-slate-600",IN_PROGRESS:"bg-blue-50 text-blue-700",AT_RISK:"bg-amber-50 text-amber-700",DELAYED:"bg-red-50 text-red-700",COMPLETED:"bg-emerald-50 text-emerald-700",CANCELLED:"bg-slate-100 text-slate-500"};
async function readJson<T>(response:Response):Promise<T>{const body=await response.json().catch(()=>({})) as {message?:string};if(!response.ok)throw new Error(body.message??`Yêu cầu thất bại (${response.status}).`);return body as T;}
function toInput(item:Milestone):MilestoneInput{return {contractId:item.contractId,workScopeId:item.workScopeId,contractItemId:item.contractItemId,ownerUserId:item.ownerUserId,code:item.code,name:item.name,description:item.description,plannedDate:item.plannedDate,forecastDate:item.forecastDate,actualDate:item.actualDate,progressPercent:item.progressPercent,status:item.status,critical:item.critical,notes:item.notes};}

export default function MilestonesPage(){
  const [milestones,setMilestones]=useState<Milestone[]>([]);const [summary,setSummary]=useState<MilestoneSummary>({total:0,completed:0,delayed:0,atRisk:0,criticalOpen:0});const [options,setOptions]=useState<MilestoneOptions>({contracts:[],workScopes:[],contractItems:[],personnel:[]});
  const [canManage,setCanManage]=useState(false);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState<string>();const [showForm,setShowForm]=useState(false);const [editing,setEditing]=useState<Milestone>();const [form,setForm]=useState<MilestoneInput>(emptyForm());const [contractFilter,setContractFilter]=useState("");const [statusFilter,setStatusFilter]=useState("");
  const load=useCallback(async()=>{const result=await readJson<{milestones:Milestone[];summary:MilestoneSummary;options:MilestoneOptions;capabilities:{canManage:boolean}}>(await fetch("/api/milestones",{cache:"no-store"}));setMilestones(result.milestones);setSummary(result.summary);setOptions(result.options);setCanManage(result.capabilities.canManage);setLoading(false);setError(undefined);},[]);
  useEffect(()=>{let active=true;const timer=window.setTimeout(()=>{void load().catch((reason)=>{if(active){setError(reason instanceof Error?reason.message:"Không thể tải mốc tiến độ.");setLoading(false);}});},0);return()=>{active=false;window.clearTimeout(timer);};},[load]);
  const scopes=useMemo(()=>options.workScopes.filter((item)=>item.contractId===form.contractId),[options.workScopes,form.contractId]);const items=useMemo(()=>options.contractItems.filter((item)=>item.contractId===form.contractId),[options.contractItems,form.contractId]);const visible=useMemo(()=>milestones.filter((item)=>(!contractFilter||item.contractId===contractFilter)&&(!statusFilter||item.status===statusFilter)),[milestones,contractFilter,statusFilter]);
  function openCreate(){const next=emptyForm();next.contractId=options.contracts[0]?.id??"";setEditing(undefined);setForm(next);setShowForm(true);setError(undefined);}function openEdit(item:Milestone){setEditing(item);setForm(toInput(item));setShowForm(true);setError(undefined);}
  function changeStatus(status:MilestoneStatus){setForm((value)=>({...value,status,progressPercent:status==="COMPLETED"?100:value.progressPercent,actualDate:status==="COMPLETED"?(value.actualDate??today()):undefined}));}
  async function save(event:FormEvent){event.preventDefault();setSaving(true);setError(undefined);try{if(editing){await readJson(await fetch(`/api/milestones/${encodeURIComponent(editing.id)}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({milestone:form,expectedVersion:editing.version})}));}else{await readJson(await fetch("/api/milestones",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)}));}setShowForm(false);await load();}catch(reason){setError(reason instanceof Error?reason.message:"Không thể lưu mốc tiến độ.");}finally{setSaving(false);}}
  return <div className="min-h-screen bg-slate-100"><AppHeader/><div className="flex"><AppSidebar/><main className="min-w-0 flex-1 p-4"><div className="mx-auto max-w-7xl">
    <div className="flex items-start justify-between gap-3"><div><h1 className="text-xl font-bold text-slate-900">Tiến độ & Mốc tiến độ</h1><p className="mt-1 text-xs text-slate-500">Theo dõi các mốc quan trọng, dự báo và mức chậm so với kế hoạch.</p></div>{canManage&&<button onClick={openCreate} className="rounded-lg bg-blue-700 px-3 py-2 text-xs font-semibold text-white">+ Thêm mốc</button>}</div>
    {error&&<p className="mt-3 rounded-lg border border-red-200 bg-red-50 p-3 text-xs text-red-700">{error}</p>}
    <div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[["Tổng mốc",summary.total,"text-slate-900"],["Hoàn thành",summary.completed,"text-emerald-700"],["Chậm",summary.delayed,"text-red-700"],["Có nguy cơ",summary.atRisk,"text-amber-700"],["Trọng yếu chưa xong",summary.criticalOpen,"text-blue-700"]].map(([label,value,color])=><div key={String(label)} className="rounded-xl border bg-white p-4"><p className="text-[10px] text-slate-500">{label}</p><p className={`text-2xl font-bold ${color}`}>{value}</p></div>)}</div>
    {showForm&&<form onSubmit={save} className="mt-4 rounded-xl border border-blue-100 bg-white p-4"><div className="flex items-center justify-between"><div><h2 className="text-sm font-bold">{editing?"Chỉnh sửa mốc tiến độ":"Thêm mốc tiến độ"}</h2><p className="mt-1 text-[10px] text-slate-500">Ngày thực tế chỉ được ghi khi mốc hoàn thành 100%.</p></div><button type="button" onClick={()=>setShowForm(false)} className="text-xs text-slate-500">Đóng</button></div><div className="mt-4 grid gap-3 md:grid-cols-2 lg:grid-cols-4">
      <label className="text-[11px] font-semibold lg:col-span-2">Hợp đồng *<select required disabled={Boolean(editing)} className={inputClass} value={form.contractId} onChange={(event)=>setForm((value)=>({...value,contractId:event.target.value,workScopeId:undefined,contractItemId:undefined}))}><option value="">Chọn hợp đồng</option>{options.contracts.map((item)=><option key={item.id} value={item.id}>{item.contractNumber} - {item.packageName}</option>)}</select></label><label className="text-[11px] font-semibold">Mã mốc *<input required maxLength={80} className={inputClass} value={form.code} onChange={(event)=>setForm((value)=>({...value,code:event.target.value}))}/></label><label className="text-[11px] font-semibold">Ngày kế hoạch *<input required type="date" className={inputClass} value={form.plannedDate} onChange={(event)=>setForm((value)=>({...value,plannedDate:event.target.value}))}/></label>
      <label className="text-[11px] font-semibold lg:col-span-2">Tên mốc *<input required maxLength={300} className={inputClass} value={form.name} onChange={(event)=>setForm((value)=>({...value,name:event.target.value}))}/></label><label className="text-[11px] font-semibold">Phạm vi công việc<select className={inputClass} value={form.workScopeId??""} onChange={(event)=>setForm((value)=>({...value,workScopeId:event.target.value||undefined,contractItemId:value.contractItemId&&items.find((item)=>item.id===value.contractItemId)?.workScopeId!==event.target.value?undefined:value.contractItemId}))}><option value="">Toàn hợp đồng</option>{scopes.map((item)=><option key={item.id} value={item.id}>{item.code?`${item.code} - `:""}{item.name}</option>)}</select></label><label className="text-[11px] font-semibold">Hạng mục<select className={inputClass} value={form.contractItemId??""} onChange={(event)=>{const selected=items.find((item)=>item.id===event.target.value);setForm((value)=>({...value,contractItemId:selected?.id,workScopeId:selected?.workScopeId??value.workScopeId}));}}><option value="">Không gắn hạng mục</option>{items.filter((item)=>!form.workScopeId||item.workScopeId===form.workScopeId).map((item)=><option key={item.id} value={item.id}>{item.itemCode?`${item.itemCode} - `:""}{item.name}</option>)}</select></label>
      <label className="text-[11px] font-semibold">Người phụ trách<select className={inputClass} value={form.ownerUserId??""} onChange={(event)=>setForm((value)=>({...value,ownerUserId:event.target.value||undefined}))}><option value="">Chưa chỉ định</option>{options.personnel.map((item)=><option key={item.id} value={item.id}>{item.displayName}{item.departmentCode?` - ${item.departmentCode}`:""}</option>)}</select></label><label className="text-[11px] font-semibold">Ngày dự báo<input type="date" className={inputClass} value={form.forecastDate??""} onChange={(event)=>setForm((value)=>({...value,forecastDate:event.target.value||undefined}))}/></label><label className="text-[11px] font-semibold">Trạng thái<select className={inputClass} value={form.status} onChange={(event)=>changeStatus(event.target.value as MilestoneStatus)}>{Object.entries(labels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label className="text-[11px] font-semibold">Hoàn thành (%)<input required type="number" min={0} max={100} className={inputClass} value={form.progressPercent} onChange={(event)=>setForm((value)=>({...value,progressPercent:Number(event.target.value)}))}/></label>
      <label className="text-[11px] font-semibold">Ngày thực tế<input type="date" disabled={form.status!=="COMPLETED"} className={inputClass} value={form.actualDate??""} onChange={(event)=>setForm((value)=>({...value,actualDate:event.target.value||undefined}))}/></label><label className="flex items-end gap-2 pb-2 text-[11px] font-semibold"><input type="checkbox" checked={form.critical} onChange={(event)=>setForm((value)=>({...value,critical:event.target.checked}))}/> Mốc trọng yếu</label><label className="text-[11px] font-semibold md:col-span-2 lg:col-span-4">Mô tả<textarea maxLength={2000} className="mt-1 min-h-14 w-full rounded-lg border border-slate-200 p-3 text-xs" value={form.description??""} onChange={(event)=>setForm((value)=>({...value,description:event.target.value}))}/></label><label className="text-[11px] font-semibold md:col-span-2 lg:col-span-4">Ghi chú/cảnh báo<textarea maxLength={2000} className="mt-1 min-h-14 w-full rounded-lg border border-slate-200 p-3 text-xs" value={form.notes??""} onChange={(event)=>setForm((value)=>({...value,notes:event.target.value}))}/></label>
      </div><div className="mt-4 flex justify-end gap-2 border-t pt-4"><button type="button" onClick={()=>setShowForm(false)} className="h-9 rounded-lg border px-4 text-xs">Hủy</button><button disabled={saving} className="h-9 rounded-lg bg-blue-700 px-4 text-xs font-semibold text-white disabled:opacity-60">{saving?"Đang lưu...":"Lưu mốc"}</button></div></form>}
    <div className="mt-4 flex flex-wrap gap-2 rounded-xl border bg-white p-3"><select className="h-9 min-w-64 rounded-lg border px-3 text-xs" value={contractFilter} onChange={(event)=>setContractFilter(event.target.value)}><option value="">Tất cả hợp đồng</option>{options.contracts.map((item)=><option key={item.id} value={item.id}>{item.contractNumber}</option>)}</select><select className="h-9 rounded-lg border px-3 text-xs" value={statusFilter} onChange={(event)=>setStatusFilter(event.target.value)}><option value="">Tất cả trạng thái</option>{Object.entries(labels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></div>
    <section className="mt-3 overflow-hidden rounded-xl border bg-white"><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="bg-slate-50 text-[10px] uppercase text-slate-500"><tr><th className="px-4 py-3">Mốc tiến độ</th><th className="px-4 py-3">Hợp đồng / phạm vi</th><th className="px-4 py-3">Kế hoạch / dự báo</th><th className="px-4 py-3">Tiến độ</th><th className="px-4 py-3">Phụ trách</th><th className="px-4 py-3">Trạng thái</th>{canManage&&<th className="px-4 py-3 text-right">Thao tác</th>}</tr></thead><tbody className="divide-y">{visible.map((item)=><tr key={item.id}><td className="px-4 py-3"><p className="font-bold text-blue-700">{item.code}{item.critical&&<span className="ml-2 text-red-600">●</span>}</p><p className="mt-1 max-w-xs text-[10px] text-slate-600">{item.name}</p></td><td className="px-4 py-3"><p className="font-semibold">{item.contractNumber}</p><p className="mt-1 text-[10px] text-slate-500">{item.contractItemName??item.workScopeName??"Toàn hợp đồng"}</p></td><td className="px-4 py-3"><p>{item.plannedDate}</p><p className={`mt-1 text-[10px] ${item.delayDays>0?"font-semibold text-red-600":"text-slate-500"}`}>{item.forecastDate?`Dự báo ${item.forecastDate}`:"Chưa có dự báo"}{item.delayDays>0?` · chậm ${item.delayDays} ngày`:""}</p></td><td className="px-4 py-3"><div className="h-1.5 w-24 rounded-full bg-slate-100"><div className="h-1.5 rounded-full bg-blue-600" style={{width:`${item.progressPercent}%`}}/></div><p className="mt-1 text-[10px] font-semibold">{item.progressPercent}%</p></td><td className="px-4 py-3">{item.ownerDisplayName??"—"}</td><td className="px-4 py-3"><span className={`rounded-full px-2 py-1 text-[10px] font-semibold ${colors[item.status]}`}>{labels[item.status]}</span></td>{canManage&&<td className="px-4 py-3 text-right"><button onClick={()=>openEdit(item)} className="font-semibold text-blue-700">Sửa</button></td>}</tr>)}{!loading&&visible.length===0&&<tr><td colSpan={7} className="p-8 text-center text-slate-500">Chưa có mốc tiến độ phù hợp.</td></tr>}</tbody></table>{loading&&<p className="p-8 text-center text-xs text-slate-500">Đang tải dữ liệu...</p>}</div></section>
  </div></main></div></div>;
}
