"use client";

import {type FormEvent,useCallback,useEffect,useMemo,useState} from "react";
import {AppHeader} from "@/components/layout/app-header";import {AppSidebar} from "@/components/layout/app-sidebar";
import type {IssueCategory,IssueSeverity,IssueStatus,TechnicalIssue,TechnicalIssueInput,TechnicalIssueOptions,TechnicalIssueSummary} from "@/types/technical-issue";

const inputClass="mt-1 h-9 w-full rounded-lg border border-slate-200 bg-white px-3 text-xs outline-none focus:border-blue-500";const today=()=>new Date().toLocaleDateString("en-CA");
const empty=():TechnicalIssueInput=>({contractId:"",code:"",title:"",description:"",category:"TECHNICAL",severity:"MEDIUM",status:"OPEN",discoveredDate:today()});
const statusLabels:Record<IssueStatus,string>={OPEN:"Mới mở",IN_PROGRESS:"Đang xử lý",PENDING_VERIFICATION:"Chờ xác nhận",RESOLVED:"Đã xử lý",CLOSED:"Đã đóng",CANCELLED:"Hủy"};
const statusColors:Record<IssueStatus,string>={OPEN:"bg-red-50 text-red-700",IN_PROGRESS:"bg-blue-50 text-blue-700",PENDING_VERIFICATION:"bg-amber-50 text-amber-700",RESOLVED:"bg-emerald-50 text-emerald-700",CLOSED:"bg-slate-100 text-slate-600",CANCELLED:"bg-slate-100 text-slate-500"};
const severityLabels:Record<IssueSeverity,string>={LOW:"Thấp",MEDIUM:"Trung bình",HIGH:"Cao",CRITICAL:"Nghiêm trọng"};const categoryLabels:Record<IssueCategory,string>={TECHNICAL:"Kỹ thuật",QUALITY:"Chất lượng",SAFETY:"An toàn",ENVIRONMENT:"Môi trường",SCHEDULE:"Tiến độ",OTHER:"Khác"};
async function json<T>(response:Response):Promise<T>{const body=await response.json().catch(()=>({})) as {message?:string};if(!response.ok)throw new Error(body.message??`Yêu cầu thất bại (${response.status}).`);return body as T;}
const toInput=(x:TechnicalIssue):TechnicalIssueInput=>({contractId:x.contractId,inspectionId:x.inspectionId,workScopeId:x.workScopeId,contractItemId:x.contractItemId,assigneeUserId:x.assigneeUserId,code:x.code,title:x.title,description:x.description,category:x.category,severity:x.severity,status:x.status,discoveredDate:x.discoveredDate,dueDate:x.dueDate,resolvedDate:x.resolvedDate,resolution:x.resolution});

export default function IssuesPage(){
  const [rows,setRows]=useState<TechnicalIssue[]>([]);const [summary,setSummary]=useState<TechnicalIssueSummary>({total:0,open:0,overdue:0,criticalOpen:0,resolved:0});const [options,setOptions]=useState<TechnicalIssueOptions>({contracts:[],inspections:[],workScopes:[],contractItems:[],personnel:[]});const [canManage,setCanManage]=useState(false);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState<string>();const [editing,setEditing]=useState<TechnicalIssue>();const [showForm,setShowForm]=useState(false);const [form,setForm]=useState<TechnicalIssueInput>(empty());const [contractFilter,setContractFilter]=useState("");const [statusFilter,setStatusFilter]=useState("");
  const load=useCallback(async()=>{const data=await json<{issues:TechnicalIssue[];summary:TechnicalIssueSummary;options:TechnicalIssueOptions;capabilities:{canManage:boolean}}>(await fetch("/api/issues",{cache:"no-store"}));setRows(data.issues);setSummary(data.summary);setOptions(data.options);setCanManage(data.capabilities.canManage);setLoading(false);setError(undefined);},[]);
  useEffect(()=>{let active=true;const timer=window.setTimeout(()=>{void load().catch((reason)=>{if(active){setError(reason instanceof Error?reason.message:"Không thể tải vấn đề kỹ thuật.");setLoading(false);}});},0);return()=>{active=false;window.clearTimeout(timer);};},[load]);
  const inspections=useMemo(()=>options.inspections.filter((x)=>x.contractId===form.contractId),[options.inspections,form.contractId]);const scopes=useMemo(()=>options.workScopes.filter((x)=>x.contractId===form.contractId),[options.workScopes,form.contractId]);const items=useMemo(()=>options.contractItems.filter((x)=>x.contractId===form.contractId),[options.contractItems,form.contractId]);const visible=useMemo(()=>rows.filter((x)=>(!contractFilter||x.contractId===contractFilter)&&(!statusFilter||x.status===statusFilter)),[rows,contractFilter,statusFilter]);
  function create(){const next=empty();next.contractId=options.contracts[0]?.id??"";setEditing(undefined);setForm(next);setShowForm(true);setError(undefined);}function edit(row:TechnicalIssue){setEditing(row);setForm(toInput(row));setShowForm(true);setError(undefined);}function changeStatus(status:IssueStatus){const done=status==="RESOLVED"||status==="CLOSED";setForm((v)=>({...v,status,resolvedDate:done?(v.resolvedDate??today()):undefined,resolution:done?v.resolution:undefined}));}
  async function save(event:FormEvent){event.preventDefault();setSaving(true);setError(undefined);try{if(editing)await json(await fetch(`/api/issues/${encodeURIComponent(editing.id)}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({issue:form,expectedVersion:editing.version})}));else await json(await fetch("/api/issues",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)}));setShowForm(false);await load();}catch(reason){setError(reason instanceof Error?reason.message:"Không thể lưu vấn đề kỹ thuật.");}finally{setSaving(false);}}
  return <div className="min-h-screen bg-slate-100"><AppHeader/><div className="flex"><AppSidebar/><main className="min-w-0 flex-1 p-4"><div className="mx-auto max-w-7xl">
    <div className="flex items-start justify-between gap-3"><div><h1 className="text-xl font-bold text-slate-900">Tồn tại / Vấn đề kỹ thuật</h1><p className="mt-1 text-xs text-slate-500">Theo dõi trách nhiệm, thời hạn, mức độ và kết quả khắc phục.</p></div>{canManage&&<button onClick={create} className="rounded-lg bg-blue-700 px-3 py-2 text-xs font-semibold text-white">+ Thêm vấn đề</button>}</div>
    {error&&<p className="mt-3 rounded-lg border border-red-200 bg-red-50 p-3 text-xs text-red-700">{error}</p>}
    <div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[["Tổng vấn đề",summary.total,"text-slate-900"],["Đang mở",summary.open,"text-blue-700"],["Quá hạn",summary.overdue,"text-red-700"],["Nghiêm trọng chưa đóng",summary.criticalOpen,"text-red-700"],["Đã xử lý/đóng",summary.resolved,"text-emerald-700"]].map(([label,value,color])=><div key={String(label)} className="rounded-xl border bg-white p-4"><p className="text-[10px] text-slate-500">{label}</p><p className={`text-2xl font-bold ${color}`}>{value}</p></div>)}</div>
    {showForm&&<form onSubmit={save} className="mt-4 rounded-xl border border-blue-100 bg-white p-4"><div className="flex justify-between"><div><h2 className="text-sm font-bold">{editing?"Chỉnh sửa vấn đề":"Thêm vấn đề kỹ thuật"}</h2><p className="mt-1 text-[10px] text-slate-500">Khi hoàn tất phải nhập ngày và nội dung xử lý.</p></div><button type="button" onClick={()=>setShowForm(false)} className="text-xs text-slate-500">Đóng</button></div><div className="mt-4 grid gap-3 md:grid-cols-2 lg:grid-cols-4">
      <label className="text-[11px] font-semibold lg:col-span-2">Hợp đồng *<select required disabled={Boolean(editing)} className={inputClass} value={form.contractId} onChange={(e)=>setForm((v)=>({...v,contractId:e.target.value,inspectionId:undefined,workScopeId:undefined,contractItemId:undefined}))}><option value="">Chọn hợp đồng</option>{options.contracts.map((x)=><option key={x.id} value={x.id}>{x.contractNumber} - {x.packageName}</option>)}</select></label><label className="text-[11px] font-semibold">Mã vấn đề *<input required maxLength={80} className={inputClass} value={form.code} onChange={(e)=>setForm((v)=>({...v,code:e.target.value}))}/></label><label className="text-[11px] font-semibold">Ngày phát hiện *<input required type="date" className={inputClass} value={form.discoveredDate} onChange={(e)=>setForm((v)=>({...v,discoveredDate:e.target.value}))}/></label>
      <label className="text-[11px] font-semibold lg:col-span-2">Tiêu đề *<input required maxLength={300} className={inputClass} value={form.title} onChange={(e)=>setForm((v)=>({...v,title:e.target.value}))}/></label><label className="text-[11px] font-semibold">Nhóm<select className={inputClass} value={form.category} onChange={(e)=>setForm((v)=>({...v,category:e.target.value as IssueCategory}))}>{Object.entries(categoryLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label className="text-[11px] font-semibold">Mức độ<select className={inputClass} value={form.severity} onChange={(e)=>setForm((v)=>({...v,severity:e.target.value as IssueSeverity}))}>{Object.entries(severityLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>
      <label className="text-[11px] font-semibold">Phiếu kiểm tra nguồn<select className={inputClass} value={form.inspectionId??""} onChange={(e)=>setForm((v)=>({...v,inspectionId:e.target.value||undefined}))}><option value="">Không liên kết</option>{inspections.map((x)=><option key={x.id} value={x.id}>{x.code} - {x.title}</option>)}</select></label><label className="text-[11px] font-semibold">Phạm vi<select className={inputClass} value={form.workScopeId??""} onChange={(e)=>setForm((v)=>({...v,workScopeId:e.target.value||undefined,contractItemId:undefined}))}><option value="">Toàn hợp đồng</option>{scopes.map((x)=><option key={x.id} value={x.id}>{x.code?`${x.code} - `:""}{x.name}</option>)}</select></label><label className="text-[11px] font-semibold">Hạng mục<select className={inputClass} value={form.contractItemId??""} onChange={(e)=>{const item=items.find((x)=>x.id===e.target.value);setForm((v)=>({...v,contractItemId:item?.id,workScopeId:item?.workScopeId??v.workScopeId}));}}><option value="">Không gắn hạng mục</option>{items.filter((x)=>!form.workScopeId||x.workScopeId===form.workScopeId).map((x)=><option key={x.id} value={x.id}>{x.itemCode?`${x.itemCode} - `:""}{x.name}</option>)}</select></label><label className="text-[11px] font-semibold">Người phụ trách<select className={inputClass} value={form.assigneeUserId??""} onChange={(e)=>setForm((v)=>({...v,assigneeUserId:e.target.value||undefined}))}><option value="">Chưa chỉ định</option>{options.personnel.map((x)=><option key={x.id} value={x.id}>{x.displayName}{x.departmentCode?` - ${x.departmentCode}`:""}</option>)}</select></label>
      <label className="text-[11px] font-semibold">Hạn xử lý<input type="date" className={inputClass} value={form.dueDate??""} onChange={(e)=>setForm((v)=>({...v,dueDate:e.target.value||undefined}))}/></label><label className="text-[11px] font-semibold">Trạng thái<select className={inputClass} value={form.status} onChange={(e)=>changeStatus(e.target.value as IssueStatus)}>{Object.entries(statusLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label className="text-[11px] font-semibold">Ngày xử lý<input type="date" disabled={form.status!=="RESOLVED"&&form.status!=="CLOSED"} className={inputClass} value={form.resolvedDate??""} onChange={(e)=>setForm((v)=>({...v,resolvedDate:e.target.value||undefined}))}/></label><label className="text-[11px] font-semibold md:col-span-2 lg:col-span-4">Mô tả vấn đề *<textarea required maxLength={6000} className="mt-1 min-h-20 w-full rounded-lg border p-3 text-xs" value={form.description} onChange={(e)=>setForm((v)=>({...v,description:e.target.value}))}/></label><label className="text-[11px] font-semibold md:col-span-2 lg:col-span-4">Nội dung xử lý{(form.status==="RESOLVED"||form.status==="CLOSED")&&" *"}<textarea required={form.status==="RESOLVED"||form.status==="CLOSED"} disabled={form.status!=="RESOLVED"&&form.status!=="CLOSED"} maxLength={6000} className="mt-1 min-h-16 w-full rounded-lg border p-3 text-xs disabled:bg-slate-50" value={form.resolution??""} onChange={(e)=>setForm((v)=>({...v,resolution:e.target.value}))}/></label>
    </div><div className="mt-4 flex justify-end gap-2 border-t pt-4"><button type="button" onClick={()=>setShowForm(false)} className="h-9 rounded-lg border px-4 text-xs">Hủy</button><button disabled={saving} className="h-9 rounded-lg bg-blue-700 px-4 text-xs font-semibold text-white disabled:opacity-60">{saving?"Đang lưu...":"Lưu vấn đề"}</button></div></form>}
    <div className="mt-4 flex flex-wrap gap-2 rounded-xl border bg-white p-3"><select className="h-9 min-w-64 rounded-lg border px-3 text-xs" value={contractFilter} onChange={(e)=>setContractFilter(e.target.value)}><option value="">Tất cả hợp đồng</option>{options.contracts.map((x)=><option key={x.id} value={x.id}>{x.contractNumber}</option>)}</select><select className="h-9 rounded-lg border px-3 text-xs" value={statusFilter} onChange={(e)=>setStatusFilter(e.target.value)}><option value="">Tất cả trạng thái</option>{Object.entries(statusLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></div>
    <section className="mt-3 overflow-hidden rounded-xl border bg-white"><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="bg-slate-50 text-[10px] uppercase text-slate-500"><tr><th className="px-4 py-3">Vấn đề</th><th className="px-4 py-3">Hợp đồng / đối tượng</th><th className="px-4 py-3">Mức độ</th><th className="px-4 py-3">Hạn xử lý</th><th className="px-4 py-3">Phụ trách</th><th className="px-4 py-3">Trạng thái</th>{canManage&&<th className="px-4 py-3 text-right">Thao tác</th>}</tr></thead><tbody className="divide-y">{visible.map((x)=><tr key={x.id}><td className="px-4 py-3"><p className="font-bold text-blue-700">{x.code}</p><p className="mt-1 max-w-xs text-[10px] text-slate-600">{x.title}</p>{x.inspectionCode&&<p className="mt-1 text-[9px] text-slate-400">Từ phiếu {x.inspectionCode}</p>}</td><td className="px-4 py-3"><p className="font-semibold">{x.contractNumber}</p><p className="mt-1 text-[10px] text-slate-500">{x.contractItemName??x.workScopeName??"Toàn hợp đồng"}</p></td><td className={`px-4 py-3 font-semibold ${x.severity==="CRITICAL"||x.severity==="HIGH"?"text-red-700":"text-slate-700"}`}>{severityLabels[x.severity]}<p className="mt-1 text-[9px] font-normal text-slate-400">{categoryLabels[x.category]}</p></td><td className="px-4 py-3"><p>{x.dueDate??"—"}</p>{x.overdueDays>0&&<p className="mt-1 text-[10px] font-semibold text-red-600">Quá {x.overdueDays} ngày</p>}</td><td className="px-4 py-3">{x.assigneeDisplayName??"—"}</td><td className="px-4 py-3"><span className={`rounded-full px-2 py-1 text-[10px] font-semibold ${statusColors[x.status]}`}>{statusLabels[x.status]}</span></td>{canManage&&<td className="px-4 py-3 text-right"><button onClick={()=>edit(x)} className="font-semibold text-blue-700">Sửa</button></td>}</tr>)}{!loading&&visible.length===0&&<tr><td colSpan={7} className="p-8 text-center text-slate-500">Chưa có vấn đề kỹ thuật phù hợp.</td></tr>}</tbody></table>{loading&&<p className="p-8 text-center text-xs text-slate-500">Đang tải dữ liệu...</p>}</div></section>
  </div></main></div></div>;
}
