import "server-only";
import type {PoolClient} from "pg";
import type {Inspection,InspectionInput,InspectionOptions,InspectionSummary} from "../../types/inspection";

const optional=(value:unknown)=>value===null?undefined:String(value);
const date=(value:unknown)=>value instanceof Date?value.toISOString().slice(0,10):String(value).slice(0,10);
const select=`SELECT x.*,c.contract_number,c.package_name,w.name work_scope_name,i.item_name contract_item_name,u.display_name inspector_display_name,
  (SELECT count(*)::int FROM tcms.technical_issues q WHERE q.inspection_id=x.id AND q.status NOT IN ('RESOLVED','CLOSED','CANCELLED')) open_issue_count
  FROM tcms.inspections x JOIN tcms.contracts c ON c.id=x.contract_id LEFT JOIN tcms.work_scopes w ON w.id=x.work_scope_id
  LEFT JOIN tcms.contract_items i ON i.id=x.contract_item_id LEFT JOIN tcms.app_users u ON u.id=x.inspector_user_id WHERE true`;
function map(row:Record<string,unknown>):Inspection{return {id:String(row.id),contractId:String(row.contract_id),contractNumber:String(row.contract_number),packageName:String(row.package_name),workScopeId:optional(row.work_scope_id),workScopeName:optional(row.work_scope_name),contractItemId:optional(row.contract_item_id),contractItemName:optional(row.contract_item_name),inspectorUserId:optional(row.inspector_user_id),inspectorDisplayName:optional(row.inspector_display_name),code:String(row.code),title:String(row.title),inspectionDate:date(row.inspection_date),inspectionType:row.inspection_type as Inspection["inspectionType"],location:optional(row.location),result:row.result as Inspection["result"],summary:optional(row.summary),recommendations:optional(row.recommendations),nextInspectionDate:row.next_inspection_date?date(row.next_inspection_date):undefined,openIssueCount:Number(row.open_issue_count),version:Number(row.version),createdAt:String(row.created_at),updatedAt:String(row.updated_at)};}
function dbError(error:unknown):never{if(typeof error==="object"&&error!==null&&"code" in error){if(error.code==="23505")throw new Error("INSPECTION_CODE_CONFLICT");if(error.code==="23503")throw new Error("INSPECTION_REFERENCE_NOT_FOUND");if(error.code==="23514")throw new SyntaxError("INVALID_INSPECTION_FIELDS");}throw error;}

export class PostgresInspectionRepository{
  constructor(private readonly client:PoolClient){}
  async list(){const result=await this.client.query(`${select} ORDER BY x.inspection_date DESC,x.code`);return result.rows.map(map);}
  async findById(id:string){const result=await this.client.query(`${select} AND x.id=$1`,[id]);return result.rowCount?map(result.rows[0]):null;}
  async summary():Promise<InspectionSummary>{const result=await this.client.query(`SELECT count(*)::int total,count(*) FILTER(WHERE result='PENDING')::int pending,count(*) FILTER(WHERE result='CONFORMING_WITH_FINDINGS')::int with_findings,count(*) FILTER(WHERE result='NONCONFORMING')::int nonconforming,count(*) FILTER(WHERE date_trunc('month',inspection_date)=date_trunc('month',current_date))::int this_month FROM tcms.inspections`);const row=result.rows[0];return {total:Number(row.total),pending:Number(row.pending),withFindings:Number(row.with_findings),nonconforming:Number(row.nonconforming),thisMonth:Number(row.this_month)};}
  async options(includePersonnel:boolean):Promise<InspectionOptions>{const [contracts,scopes,items,personnel]=await Promise.all([
    this.client.query("SELECT id::text,contract_number,package_name FROM tcms.contracts WHERE archived_at IS NULL ORDER BY contract_number"),
    this.client.query("SELECT id::text,contract_id::text,code,name FROM tcms.work_scopes ORDER BY contract_id,sequence"),
    this.client.query("SELECT id::text,contract_id::text,work_scope_id::text,item_code,item_name FROM tcms.contract_items WHERE archived_at IS NULL ORDER BY contract_id,sequence_number"),
    includePersonnel?this.client.query("SELECT u.id::text,u.display_name,d.code department_code FROM tcms.app_users u LEFT JOIN tcms.departments d ON d.id=u.primary_department_id WHERE u.active ORDER BY u.display_name"):Promise.resolve({rows:[]})]);
    return {contracts:contracts.rows.map((r)=>({id:String(r.id),contractNumber:String(r.contract_number),packageName:String(r.package_name)})),workScopes:scopes.rows.map((r)=>({id:String(r.id),contractId:String(r.contract_id),code:optional(r.code),name:String(r.name)})),contractItems:items.rows.map((r)=>({id:String(r.id),contractId:String(r.contract_id),workScopeId:optional(r.work_scope_id),itemCode:optional(r.item_code),name:String(r.item_name)})),personnel:personnel.rows.map((r)=>({id:String(r.id),displayName:String(r.display_name),departmentCode:optional(r.department_code)}))};}
  async create(input:InspectionInput,actor:string){try{await this.ensureUser(input.inspectorUserId);const result=await this.client.query(`INSERT INTO tcms.inspections(contract_id,work_scope_id,contract_item_id,inspector_user_id,code,title,inspection_date,inspection_type,location,result,summary,recommendations,next_inspection_date,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$14) RETURNING id::text`,[input.contractId,input.workScopeId,input.contractItemId,input.inspectorUserId,input.code,input.title,input.inspectionDate,input.inspectionType,input.location,input.result,input.summary,input.recommendations,input.nextInspectionDate,actor]);return (await this.findById(String(result.rows[0].id)))!;}catch(error){return dbError(error);}}
  async update(id:string,version:number,input:InspectionInput,actor:string){try{await this.ensureUser(input.inspectorUserId);const result=await this.client.query(`UPDATE tcms.inspections SET contract_id=$1,work_scope_id=$2,contract_item_id=$3,inspector_user_id=$4,code=$5,title=$6,inspection_date=$7,inspection_type=$8,location=$9,result=$10,summary=$11,recommendations=$12,next_inspection_date=$13,updated_by=$14 WHERE id=$15 AND version=$16 RETURNING id`,[input.contractId,input.workScopeId,input.contractItemId,input.inspectorUserId,input.code,input.title,input.inspectionDate,input.inspectionType,input.location,input.result,input.summary,input.recommendations,input.nextInspectionDate,actor,id,version]);if(!result.rowCount)throw new Error("INSPECTION_CONCURRENT_UPDATE_OR_NOT_FOUND");return (await this.findById(id))!;}catch(error){return dbError(error);}}
  private async ensureUser(id?:string){if(!id)return;const result=await this.client.query("SELECT 1 FROM tcms.app_users WHERE id=$1 AND active",[id]);if(!result.rowCount)throw new Error("INSPECTION_PERSONNEL_NOT_AVAILABLE");}
}
